// <auto-generated />
namespace UVCourseAndResultManagementMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class version01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version01));
        
        string IMigrationMetadata.Id
        {
            get { return "201912061646082_version01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
